services:
  minecraft-server:
    build: .
    container_name: YOUR_VALUE
    ports:
      - "${SERVER_PORT:-YOUR_VALUE}:YOUR_VALUE"
    environment:
      # Configuration Minecraft
      - MINECRAFT_VERSION=${MINECRAFT_VERSION:-1.20.1}
      - MODLOADER=${MODLOADER:-Fabric}
      - MODLOADER_VERSION=${MODLOADER_VERSION:-0.16.14}
      - RECOMMENDED_JAVA_VERSION=${RECOMMENDED_JAVA_VERSION:-17}
      
            # Configuration Java. Augementer la RAM si nécessaire à 8Go --Xmx8G -Xms8G
      - JAVA_ARGS=${JAVA_ARGS:--Xmx4G -Xms4G}
      - ADDITIONAL_ARGS=${ADDITIONAL_ARGS:--Dlog4j2.formatMsgNoLookups=true}
      
      # Configuration serveur
      - RESTART=${RESTART:-true}
      - WAIT_FOR_USER_INPUT=${WAIT_FOR_USER_INPUT:-false}
      - SKIP_JAVA_CHECK=${SKIP_JAVA_CHECK:-false}
      - EULA=${EULA:-true}
      
      # Configuration Fabric
      - FABRIC_INSTALLER_VERSION=${FABRIC_INSTALLER_VERSION:-1.1.0}
      - USE_SSJ=${USE_SSJ:-true}
      - SERVERSTARTERJAR_FORCE_FETCH=${SERVERSTARTERJAR_FORCE_FETCH:-true}
      - SERVERSTARTERJAR_VERSION=${SERVERSTARTERJAR_VERSION:-latest}
      
      # Configuration JDK
      - JDK_VENDOR=${JDK_VENDOR:-temurin}
      - JABBA_INSTALL_VERSION=${JABBA_INSTALL_VERSION:-0.13.0}
      
      # Adresse IP du serveur
      - SERVER_IP=${SERVER_IP:-localhost}
    
    volumes:
      # Persistance des données
      - minecraft_world:/minecraft/world
      - minecraft_logs:/minecraft/logs
      - minecraft_backups:/minecraft/backups
      - minecraft_config:/minecraft/config
      - minecraft_mods:/minecraft/mods
      
      # Configuration serveur (optionnel - pour personnaliser)
      - ./server.properties:/minecraft/server.properties:ro
      - ./ops.json:/minecraft/ops.json:ro
      - ./whitelist.json:/minecraft/whitelist.json:ro
    
    restart: unless-stopped
    
    # Limites de ressources (optionnel)
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    
    # Réseau personnalisé (optionnel)
    networks:
      - minecraft-network

# Volumes nommés pour la persistance
volumes:
  minecraft_world:
    driver: local
  minecraft_logs:
    driver: local
  minecraft_backups:
    driver: local
  minecraft_config:
    driver: local
  minecraft_mods:
    driver: local

# Réseau personnalisé
networks:
  minecraft-network:
    driver: bridge